{
  "formatVersion": "1.1",
  "component": {
    "group": "DokitSample",
    "module": "dokit-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.didiglobal.booster",
          "module": "booster-api",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-asm",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "dokit-0.0.17.jar",
          "url": "dokit-0.0.17.jar",
          "size": 157050,
          "sha512": "c39f6254138c68ee7c79f5543cbf54d31433176256f1dc3296dc7f5ab505b6bf6afb6554d2b194e491610563b9ffbc91e6c0883f1fa70631cc84d0a5adc46747",
          "sha256": "c873c71f2c7f1e30352716fe20f044abbe39362b9f582bf0d42ebdcae7fa384e",
          "sha1": "c52523636fc8bde9bbf7af3e24df8bb6e9e4457e",
          "md5": "616009131f6574d84e32c845a20e528e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.didiglobal.booster",
          "module": "booster-api",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-asm",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "dokit-0.0.17.jar",
          "url": "dokit-0.0.17.jar",
          "size": 157050,
          "sha512": "c39f6254138c68ee7c79f5543cbf54d31433176256f1dc3296dc7f5ab505b6bf6afb6554d2b194e491610563b9ffbc91e6c0883f1fa70631cc84d0a5adc46747",
          "sha256": "c873c71f2c7f1e30352716fe20f044abbe39362b9f582bf0d42ebdcae7fa384e",
          "sha1": "c52523636fc8bde9bbf7af3e24df8bb6e9e4457e",
          "md5": "616009131f6574d84e32c845a20e528e"
        }
      ]
    }
  ]
}
